import type { Metadata } from "next";
import { IBM_Plex_Mono, Anonymous_Pro, Just_Another_Hand } from "next/font/google";
import "./globals.css";

const ibm_Plex_Mono = IBM_Plex_Mono({
  subsets: ["latin"],
  variable: "--font-ibm-plex-mono",
  weight: ["400", "700"],
});

const anonymous_Pro = Anonymous_Pro({
  subsets: ["latin"],
  variable: "--font-anonymous-pro",
  weight: ["400", "700"],
});

const just_Another_Hand = Just_Another_Hand({
  subsets: ["latin"],
  variable: "--font-just-another-hand",
  weight: ["400", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibm_Plex_Mono.variable} ${anonymous_Pro.variable} ${just_Another_Hand.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
